### ISSUE TITLE
len(catalog) is very slow

### ISSUE THREAD

**Issue by joezuntz** [yymao/generic-catalog-reader#26]
Getting the length of a catalog can be very slow - it is implemented by loading in an entire column and measuring its length.

Could this be sped up?  One option would be including the total catalog size in its configuration file, since catalogs don't typically change.

Another would be looking at file metadata rather than loading it all in.

**Comment by yymao** [comment]
@joezuntz: Because each catalog has a different underlying file format, each catalog reader is supposed the overwrite the `__len__` method to provide a more efficient implementation. This slow implementation in the base class is a just a fallback behavior. Unfortunately, most readers have not actually overwritten `__len__`. Can you open issues in https://github.com/LSSTDESC/gcr-catalogs for the particular readers/catalogs that you'd like to see improvement in `__len__`? Thanks.

**Comment by joezuntz** [comment]
Done - closing this one now
